[2024-07-13T07:08:52.548+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:08:52.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:08:52.550+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:08:52.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:08:52.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:08:52.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:00.587+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:00.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:00.589+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:00.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:00.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:00.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:02.617+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:02.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:02.620+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:02.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:02.623+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:02.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 13
    file_postfix = datetime.now().
                                  ^
SyntaxError: invalid syntax
[2024-07-13T07:09:02.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:02.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.027 seconds
[2024-07-13T07:09:06.646+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:06.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:06.648+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:06.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:06.651+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:06.650+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 13, in <module>
    file_postfix = datetime.now().strftime()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strftime() missing required argument 'format' (pos 1)
[2024-07-13T07:09:06.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:06.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:09:08.680+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:08.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:08.682+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:08.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:08.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:08.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:12.709+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:12.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:12.712+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:12.712+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:12.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:12.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:17.750+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:17.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:17.753+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:17.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:17.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:17.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:19.770+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:19.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:19.772+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:19.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:19.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:19.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.023 seconds
[2024-07-13T07:09:22.809+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:22.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:22.811+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:22.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:22.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:22.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.022 seconds
[2024-07-13T07:09:31.853+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:31.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:31.856+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:31.856+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:31.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:31.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.026 seconds
[2024-07-13T07:09:42.915+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:42.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:42.917+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:42.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:42.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:42.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.026 seconds
[2024-07-13T07:09:45.937+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:45.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:45.940+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:45.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:45.943+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:45.942+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 15, in <module>
    dag = DAG(
          ^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-07-13T07:09:45.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:45.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.033 seconds
[2024-07-13T07:09:47.978+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:47.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:47.980+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:47.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:47.983+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:47.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 16, in <module>
    da
NameError: name 'da' is not defined
[2024-07-13T07:09:47.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:48.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.029 seconds
[2024-07-13T07:09:49.001+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:49.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:49.003+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:49.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:49.006+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:49.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 16
    dag_id=
    ^^^^^^^
SyntaxError: expected argument value expression
[2024-07-13T07:09:49.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:49.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.027 seconds
[2024-07-13T07:09:58.062+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:58.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:58.065+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.064+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:58.080+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:58.263+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.263+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:etl_reddit_pipeline
[2024-07-13T07:09:58.271+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.271+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:etl_reddit_pipeline
[2024-07-13T07:09:58.276+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.275+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:etl_reddit_pipeline
[2024-07-13T07:09:58.276+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.276+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:09:58.285+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.285+0000] {dag.py:3118} INFO - Creating ORM DAG for etl_reddit_pipeline
[2024-07-13T07:09:58.294+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:58.294+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:09:58.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.250 seconds
[2024-07-13T07:09:59.336+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:59.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:09:59.338+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:59.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:59.347+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:09:59.358+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:59.358+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:09:59.380+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:09:59.380+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:09:59.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.066 seconds
[2024-07-13T07:10:09.452+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:09.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:10:09.454+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:09.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:09.463+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:09.475+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:09.475+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:10:09.495+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:09.494+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:10:09.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.066 seconds
[2024-07-13T07:10:39.552+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:39.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:10:39.555+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:39.555+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:39.563+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:10:39.672+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:39.671+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:10:39.694+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:10:39.694+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:10:39.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.162 seconds
[2024-07-13T07:11:09.817+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:09.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:11:09.819+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:09.819+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:09.827+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:09.845+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:09.844+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:11:09.868+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:09.868+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:11:09.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.073 seconds
[2024-07-13T07:11:32.977+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:32.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:11:32.980+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:32.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:32.983+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:32.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 18
    schedule_interval=
    ^^^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-07-13T07:11:32.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:33.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.091 seconds
[2024-07-13T07:11:36.995+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:36.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:11:36.997+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:36.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:37.004+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:37.001+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-07-13T07:11:37.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:37.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.032 seconds
[2024-07-13T07:11:51.054+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:51.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:11:51.219+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:51.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:51.226+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:51.223+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-07-13T07:11:51.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:51.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.199 seconds
[2024-07-13T07:11:57.118+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:57.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:11:57.122+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:57.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:57.136+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:11:57.270+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:57.270+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:11:57.297+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:11:57.297+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:11:57.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.207 seconds
[2024-07-13T07:12:02.316+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:02.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:02.319+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:02.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:02.330+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:02.343+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:02.343+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:02.370+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:02.370+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:12:02.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.083 seconds
[2024-07-13T07:12:14.412+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:14.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:14.416+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:14.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:14.430+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:14.447+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:14.447+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:14.475+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:14.475+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:12:14.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.131 seconds
[2024-07-13T07:12:16.470+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:16.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:16.472+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:16.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:16.484+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:16.498+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:16.498+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:16.525+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:16.525+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2024-07-13T07:12:16.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.083 seconds
[2024-07-13T07:12:23.501+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:23.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:23.504+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:23.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:23.517+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:23.531+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:23.531+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:23.564+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:23.563+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:12:23.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.104 seconds
[2024-07-13T07:12:44.674+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:44.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:44.677+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:44.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:44.687+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:44.801+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:44.800+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:44.820+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:44.820+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:12:44.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.167 seconds
[2024-07-13T07:12:58.740+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:58.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:12:58.742+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:58.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:58.753+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:12:58.766+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:58.765+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:12:58.788+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:12:58.788+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:12:58.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.072 seconds
[2024-07-13T07:13:01.757+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:01.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:01.759+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:01.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:01.770+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:01.782+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:01.782+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:01.804+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:01.804+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:01.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.075 seconds
[2024-07-13T07:13:04.857+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:04.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:04.860+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:04.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:04.873+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:04.885+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:04.885+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:04.908+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:04.908+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:04.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.079 seconds
[2024-07-13T07:13:08.882+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:08.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:08.886+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:08.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:08.897+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:08.911+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:08.910+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:08.937+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:08.937+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:08.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.083 seconds
[2024-07-13T07:13:35.059+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:35.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:35.062+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:35.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:35.076+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:35.187+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:35.187+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:35.237+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:35.237+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:35.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.206 seconds
[2024-07-13T07:13:45.116+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:45.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:45.118+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:45.118+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:45.129+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:45.167+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:45.166+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:45.203+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:45.202+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:45.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.162 seconds
[2024-07-13T07:13:54.156+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:54.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:54.159+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:54.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:54.170+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:54.181+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:54.181+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:54.205+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:54.204+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:54.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.071 seconds
[2024-07-13T07:13:56.255+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:56.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:13:56.257+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:56.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:56.267+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:13:56.278+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:56.278+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:13:56.300+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:13:56.300+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:13:56.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.069 seconds
[2024-07-13T07:14:13.320+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:13.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:14:13.323+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:13.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:13.335+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:13.352+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:13.352+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:14:13.375+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:13.375+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:14:13.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.080 seconds
[2024-07-13T07:14:17.407+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:17.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:14:17.409+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:17.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:17.422+0000] {processor.py:840} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:17.440+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:17.440+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T07:14:17.468+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:17.468+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_reddit_pipeline to 2024-07-12 00:00:00+00:00, run_after=2024-07-13 00:00:00+00:00
[2024-07-13T07:14:17.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.089 seconds
[2024-07-13T07:14:34.496+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:34.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:14:34.498+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:34.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:34.512+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:34.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 24, in <module>
    extract = PythonOperator
              ^^^^^^^^^^^^^^
NameError: name 'PythonOperator' is not defined
[2024-07-13T07:14:34.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:34.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.050 seconds
[2024-07-13T07:14:39.520+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:39.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:14:39.522+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:39.522+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:39.527+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:39.525+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-07-13T07:14:39.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:39.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.034 seconds
[2024-07-13T07:14:47.554+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:47.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:14:47.556+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:47.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:47.559+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:14:47.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 24
    extract = 
              ^
SyntaxError: invalid syntax
[2024-07-13T07:14:47.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:14:47.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.031 seconds
[2024-07-13T07:15:17.712+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:17.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:15:17.715+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:15:17.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:17.718+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:15:17.717+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 24
    extract = 
              ^
SyntaxError: invalid syntax
[2024-07-13T07:15:17.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:17.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.032 seconds
[2024-07-13T07:15:47.840+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:47.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:15:47.842+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:15:47.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:47.845+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:15:47.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 24
    extract = 
              ^
SyntaxError: invalid syntax
[2024-07-13T07:15:47.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:15:48.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.312 seconds
[2024-07-13T07:16:18.271+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:18.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:16:18.273+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:18.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:18.276+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:18.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 24
    extract = 
              ^
SyntaxError: invalid syntax
[2024-07-13T07:16:18.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:18.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.029 seconds
[2024-07-13T07:16:47.377+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:47.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:16:47.379+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:47.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:47.383+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:47.381+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25
    extract = 
              ^
SyntaxError: invalid syntax
[2024-07-13T07:16:47.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:47.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.030 seconds
[2024-07-13T07:16:52.431+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:52.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:16:52.432+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:52.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:52.439+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:16:52.438+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator()
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:16:52.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:16:52.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:17:00.473+0000] {processor.py:161} INFO - Started process (PID=325) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:00.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:00.475+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:00.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:00.483+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:00.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 26, in <module>
    task
NameError: name 'task' is not defined
[2024-07-13T07:17:00.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:00.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.032 seconds
[2024-07-13T07:17:04.520+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:04.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:04.522+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:04.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:04.529+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:04.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:17:04.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:04.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.031 seconds
[2024-07-13T07:17:14.577+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:14.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:14.579+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:14.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:14.591+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:14.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 26, in <module>
    taski
NameError: name 'taski' is not defined
[2024-07-13T07:17:14.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:14.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.042 seconds
[2024-07-13T07:17:15.610+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:15.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:15.611+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:15.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:15.615+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:15.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 26
    task_id=
    ^^^^^^^^
SyntaxError: expected argument value expression
[2024-07-13T07:17:15.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:15.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:17:24.681+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:24.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:24.683+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:24.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:24.695+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:24.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:17:24.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:24.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.040 seconds
[2024-07-13T07:17:27.705+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:27.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:27.706+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:27.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:27.714+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:27.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:17:27.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:27.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.034 seconds
[2024-07-13T07:17:32.769+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:32.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:32.771+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:32.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:32.779+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:32.777+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:17:32.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:32.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.034 seconds
[2024-07-13T07:17:37.804+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:37.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:37.806+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:37.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:37.814+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:37.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 25, in <module>
    extract = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-07-13T07:17:37.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:37.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.063 seconds
[2024-07-13T07:17:42.854+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:42.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:42.855+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:42.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:42.858+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:42.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 28
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-07-13T07:17:42.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:42.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.027 seconds
[2024-07-13T07:17:43.865+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:43.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:43.866+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:43.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:43.869+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:43.868+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-07-13T07:17:43.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:43.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:17:53.945+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:53.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:17:53.948+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:53.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:53.961+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:17:53.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:17:53.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:17:53.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.044 seconds
[2024-07-13T07:18:08.007+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:08.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:08.009+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:08.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:08.013+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:08.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 29
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-07-13T07:18:08.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:08.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.032 seconds
[2024-07-13T07:18:10.060+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:10.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:10.061+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:10.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:10.066+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:10.064+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 28
    op_kwargs=
    ^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-07-13T07:18:10.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:10.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.031 seconds
[2024-07-13T07:18:13.082+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:13.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:13.084+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:13.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:13.096+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:13.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:18:13.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:13.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.041 seconds
[2024-07-13T07:18:24.158+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:24.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:24.159+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:24.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:24.162+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:24.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 29
    "file_name": 
               ^
SyntaxError: expression expected after dictionary key and ':'
[2024-07-13T07:18:24.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:24.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:18:30.189+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:30.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:30.190+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:30.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:30.203+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:30.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:18:30.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:30.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.042 seconds
[2024-07-13T07:18:34.236+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:34.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:34.237+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:34.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:34.251+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:34.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:18:34.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:34.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.043 seconds
[2024-07-13T07:18:46.302+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:46.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:46.304+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:46.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:46.307+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:46.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 30
    "subreddit":
               ^
SyntaxError: expression expected after dictionary key and ':'
[2024-07-13T07:18:46.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:46.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.028 seconds
[2024-07-13T07:18:50.347+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:50.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:50.349+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:50.348+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:50.361+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:50.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:18:50.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:50.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.041 seconds
[2024-07-13T07:18:55.384+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:55.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:18:55.385+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:55.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:55.397+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:18:55.391+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:18:55.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:18:55.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.039 seconds
[2024-07-13T07:19:06.466+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:06.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:06.467+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:06.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:06.470+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:06.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 31
    time_filter
              ^
SyntaxError: ':' expected after dictionary key
[2024-07-13T07:19:06.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:06.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.026 seconds
[2024-07-13T07:19:08.488+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:08.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:08.490+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:08.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:08.493+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:08.492+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 31
    "time_filter":
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-07-13T07:19:08.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:08.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.032 seconds
[2024-07-13T07:19:09.520+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:09.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:09.522+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:09.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:09.524+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:09.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 31
    "time_filter": 
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-07-13T07:19:09.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:09.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.026 seconds
[2024-07-13T07:19:12.558+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:12.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:12.559+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:12.559+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:12.573+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:12.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:19:12.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:12.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.043 seconds
[2024-07-13T07:19:18.596+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:18.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:18.598+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:18.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:18.609+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:18.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:19:18.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:18.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.039 seconds
[2024-07-13T07:19:25.660+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:25.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:25.662+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:25.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:25.674+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:25.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:19:25.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:25.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.041 seconds
[2024-07-13T07:19:55.776+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:55.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_dag.py for tasks to queue
[2024-07-13T07:19:55.777+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:55.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:55.789+0000] {logging_mixin.py:188} INFO - [2024-07-13T07:19:55.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_dag.py", line 27, in <module>
    python_callable=reddit_pipeline,
                    ^^^^^^^^^^^^^^^
NameError: name 'reddit_pipeline' is not defined
[2024-07-13T07:19:55.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_dag.py
[2024-07-13T07:19:55.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_dag.py took 0.042 seconds
