[2024-07-14T09:25:28.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:25:28.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:25:23.511910+00:00 [queued]>
[2024-07-14T09:25:28.630+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:25:23.511910+00:00 [queued]>
[2024-07-14T09:25:28.631+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T09:25:28.643+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-14 09:25:23.511910+00:00
[2024-07-14T09:25:28.653+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:25:28.654+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2024-07-14T09:25:28.655+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-07-14T09:25:23.511910+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmp1zp6vs42']
[2024-07-14T09:25:28.657+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask s3_upload
[2024-07-14T09:25:28.705+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:25:23.511910+00:00 [running]> on host 906654fcd818
[2024-07-14T09:25:28.796+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ademola Balogun' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T09:25:23.511910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T09:25:23.511910+00:00'
[2024-07-14T09:25:28.797+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:25:29.637+0000] {logging_mixin.py:188} INFO - Bucket already exists!
[2024-07-14T09:25:29.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:25:29.638+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split("/")[-1])
                                                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-14T09:25:29.648+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-07-14T09:25:23.511910+00:00, execution_date=20240714T092523, start_date=20240714T092528, end_date=20240714T092529
[2024-07-14T09:25:29.660+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task s3_upload ('NoneType' object has no attribute 'split'; 192)
[2024-07-14T09:25:29.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T09:25:29.727+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:25:29.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
