[2024-07-14T07:20:59.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T07:20:59.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:20:57.869379+00:00 [queued]>
[2024-07-14T07:20:59.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:20:57.869379+00:00 [queued]>
[2024-07-14T07:20:59.355+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T07:20:59.368+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-07-14 07:20:57.869379+00:00
[2024-07-14T07:20:59.379+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T07:20:59.380+0000] {standard_task_runner.py:63} INFO - Started process 969 to run task
[2024-07-14T07:20:59.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-07-14T07:20:57.869379+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmp0t32le41']
[2024-07-14T07:20:59.383+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask reddit_extraction
[2024-07-14T07:20:59.432+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:20:57.869379+00:00 [running]> on host 12ac62825425
[2024-07-14T07:20:59.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ademola Balogun' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:20:57.869379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T07:20:57.869379+00:00'
[2024-07-14T07:20:59.536+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T07:20:59.553+0000] {logging_mixin.py:188} INFO - Connected to reddit
[2024-07-14T07:21:00.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T07:21:00.159+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 17, in reddit_pipeline
    load_data_to_csv(posts_df, OUTPUT_PATH)
  File "/opt/airflow/etls/reddit_etl.py", line 44, in load_data_to_csv
    data.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/output'
[2024-07-14T07:21:00.175+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-07-14T07:20:57.869379+00:00, execution_date=20240714T072057, start_date=20240714T072059, end_date=20240714T072100
[2024-07-14T07:21:00.189+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task reddit_extraction ([Errno 21] Is a directory: '/opt/airflow/data/output'; 969)
[2024-07-14T07:21:00.236+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T07:21:00.257+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T07:21:00.258+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
